name: notes_mvvm
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.5
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  path: ^1.8.2
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6
  image_picker: ^0.8.7+3
  lottie: ^2.3.2
  intl: ^0.17.0
  flutter_fadein: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mockito: ^5.4.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  flutter_localizations:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/images/core/icon.png"
  image_path_ios: "assets/images/core/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#58b9f0"

flutter_native_splash:
  background_image: "assets/images/welcome/splash_light.png"
  background_image_dark: "assets/images/welcome/splash_dark.png"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/json/
    - assets/images/welcome/
    - assets/images/core/
    - assets/images/core/dialog_widget_icons/
    - assets/images/app_icons/
    - assets/images/app_icons/screens_icons/
    - assets/images/app_icons/languages_icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 900
    - family: tajawal
      fonts:
        - asset: assets/fonts/tajawal.ttf
        - asset: assets/fonts/tajawal_bold.ttf
          weight: 900